### ISSUE TITLE
NOD sticker changes

### ISSUE THREAD

**Issue by JasperWallace** [londonhackspace/wasp-label-printer#4]
Needs name of issuer + date at a minimum

**Comment by marksteward** [comment]
Also needs to notify the list or be visible online.

**Comment by JasperWallace** [comment]
partly done by 73f7db030f283fdf36f41528ea0f70a8b2c1eb73

**Comment by russss** [comment]
I'd argue that adding enough info to the sticker for it to be usefully logged online would slow down the process of applying a number of stickers, as you'd have to keep running back and forth between the items you're stickering and the kiosk. Especially a pain if you're stickering stuff downstairs.

Would recommend closing this for the moment and seeing how things progress. We could add some text to the sticker to the effect of "this notice isn't valid unless the mailing list has been notified about it".
