### ISSUE TITLE
Unicode characters printed as their long-form code point

### ISSUE THREAD

**Issue by paullessing** [londonhackspace/wasp-label-printer#7]
Unicode characters in the storage request are printed as their unicode code-point, e.g. `'` gets transformed to `#0027;` before printing. See for example storage request https://london.hackspace.org.uk/storage/367.

I suspect the problem is in [waspd.py#L113](https://github.com/londonhackspace/wasp-label-printer/blob/master/waspd.py#L113) but am not sure.

**Comment by JasperWallace** [comment]
I don't think so, i think it's somewhere in the http stuff.
```
>>> s = "x 2' squ"
>>> s.encode('cp850', 'replace')
"x 2' squ"
>>> 
```

**Comment by paullessing** [comment]
OK, I was just taking a stab at where I thought the issue might be.

**Comment by JasperWallace** [comment]
`
Mar  1 21:02:31 kiosk waspd[2153]: INFO     Command: POST Path: /print/dnh Headers: [('host', 'kiosk.london.hackspace.org.uk: 12345'), ('content-type', 'application/json'), ('content-length', '518'), ('accept', '*/*')]
Mar  1 21:02:31 kiosk waspd[2153]: INFO     {u'name': u'Sheets of MDF', u'max_extention': u'14', u'completion_date': u'2016/04/30', u'ownername': u'Paul Lessing', u'storage_id': u'367', u'more_info': u'There are two sheets, one 4&#39; by 2&#39;, one approx 2&#39; square. I bought them for laser cutting into a travel Dominion card holder, but didn&#39;t finish the whole thing, and also overbought by one sheet. \r\nThe small sheet should be used up before the 11th March. \r\nI was hoping to store the larger sheet for a little longer until I have another project I need it for. '}
Mar  1 21:02:31 kiosk waspd[2153]: INFO     "POST /print/dnh HTTP/1.1" 200 -
`

It's coming from the website.

The description is stored in the db that way.
